module [Model]

import Time
import Style exposing [Style]

# A cursor is just a single character animation
# A spinner is a multiple character animation
# I should just support linear animation and then add easing
# A progress bar is just a fancy spinner

defaultBlinkSpeed = 530

## Describes the behavior of the cursor.
Mode : [Blink, Static, Hide]

## Model for this cursor element.
Model : {
    # The style used for the cursor block.
    style : Style,
    # The style used for the cursor when it is hidden (when blinking).
    textStyle : Style,
    # char is the character under the cursor
    char : Str,
    focus : Bool,
    blinkSpeed : Time.Duration,
    # mode determines the behavior of the cursor
    mode : Mode,
}

# init : Model
init = {
    blink: {
        speed: defaultBlinkSpeed,
    },
    mode: Blink,
}

## Update updates the cursor.
# func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
#    switch msg := msg.(type) {
#    case initialBlinkMsg:
#        # We accept all initialBlinkMsgs generated by the Blink command.

#        if m.mode != CursorBlink || !m.focus {
#            return m, nil
#        }

#        cmd := m.BlinkCmd()
#        return m, cmd

#    case BlinkMsg:
#        # We're choosy about whether to accept blinkMsgs so that our cursor
#        # only exactly when it should.

#        # Is this model blink-able?
#        if m.mode != CursorBlink || !m.focus {
#            return m, nil
#        }

#        # Were we expecting this blink message?
#        if msg.id != m.id || msg.tag != m.blinkTag {
#            return m, nil
#        }

#        var cmd tea.Cmd
#        if m.mode == CursorBlink {
#            m.Blink = !m.Blink
#            cmd = m.BlinkCmd()
#        }
#        return m, cmd

#    case blinkCanceled: # no-op
#        return m, nil
#    }
#    return m, nil
# }

## SetMode sets the model's cursor mode. This method returns a command.
##
## For available cursor modes, see type CursorMode.
# func (m *Model) SetMode(mode Mode) tea.Cmd {
#    # Adjust the mode value if it's value is out of range
#    if mode < CursorBlink || mode > CursorHide {
#        return nil
#    }
#    m.mode = mode
#    m.Blink = m.mode == CursorHide || !m.focus
#    if mode == CursorBlink {
#        return Blink
#    }
#    return nil
# }

## BlinkCmd is a command used to manage cursor blinking.
# func (m *Model) BlinkCmd() tea.Cmd {
#    if m.mode != CursorBlink {
#        return nil
#    }

#    if m.blinkCtx != nil && m.blinkCtx.cancel != nil {
#        m.blinkCtx.cancel()
#    }

#    ctx, cancel := context.WithTimeout(m.blinkCtx.ctx, m.BlinkSpeed)
#    m.blinkCtx.cancel = cancel

#    m.blinkTag++

#    return func() tea.Msg {
#        defer cancel()
#        <-ctx.Done()
#        if ctx.Err() == context.DeadlineExceeded {
#            return BlinkMsg{id: m.id, tag: m.blinkTag}
#        }
#        return blinkCanceled{}
#    }
# }

## Blink is a command used to initialize cursor blinking.
# func Blink() tea.Msg {
#    return initialBlinkMsg{}
# }

## Focus focuses the cursor to allow it to blink if desired.
# func (m *Model) Focus() tea.Cmd {
#    m.focus = true
#    m.Blink = m.mode == CursorHide # show the cursor unless we've explicitly hidden it

#    if m.mode == CursorBlink && m.focus {
#        return m.BlinkCmd()
#    }
#    return nil
# }

## View displays the cursor.
# func (m Model) View() string {
#    if m.Blink {
#        return m.TextStyle.Inline(true).Render(m.char)
#    }
#    return m.Style.Inline(true).Reverse(true).Render(m.char)
# }
